### ISSUE TITLE
signing is trying to sign a storyboard bundle, and is erroring out on the storyboard's info plist file

### ISSUE THREAD

**Issue by catshow** [indygreg/apple-platform-rs#38]
Log:
```
[2022-11-04T02:47:05Z WARN  re_sign::util] signing /tmp/i1/Payload/iOSTestApp.app to /var/folders/k1/fyztggjd12x7v_br1g23xxfh0000gn/T/.tmpqPvRzt
[2022-11-04T02:47:05Z WARN  apple_codesign::signing] signing bundle at /tmp/i1/Payload/iOSTestApp.app
[2022-11-04T02:49:11Z WARN  apple_codesign::bundle_signing] signing 2 nested bundles in the following order:
[2022-11-04T02:49:13Z WARN  apple_codesign::bundle_signing] Base.lproj/LaunchScreen.storyboardc
[2022-11-04T02:49:14Z WARN  apple_codesign::bundle_signing] Base.lproj/Main.storyboardc
[2022-11-04T02:52:13Z INFO  apple_codesign::bundle_signing] entering nested bundle /tmp/i1/Payload/iOSTestApp.app/Base.lproj/LaunchScreen.storyboardc
[2022-11-04T02:52:13Z WARN  apple_codesign::bundle_signing] signing bundle at /tmp/i1/Payload/iOSTestApp.app/Base.lproj/LaunchScreen.storyboardc into /var/folders/k1/fyztggjd12x7v_br1g23xxfh0000gn/T/.tmpqPvRzt/Base.lproj/LaunchScreen.storyboardc
Error: bundle Info.plist does not define CFBundleIdentifier: /tmp/i1/Payload/iOSTestApp.app/Base.lproj/LaunchScreen.storyboardc/Info.plist
```

If you give me a hint on how to fix, I can look at submitting a PR.

**Comment by indygreg** [comment]
I've never seen a storyboard bundle before! I didn't even know that was a thing!

This may warrant a new bundle categorization type. I'm just not sure!

I guess next steps are reading docs about storyboard bundles, if there are any.

**Comment by catshow** [comment]
I fixed this on my version, unfortunately I can't contribute it back until I have clearance.  I suggest that you check the CFBundlePackageType after reading the info plist.  If you can't find that, do a second check to see if there is a bundle identifier inside of the plist, and if there is, just assume it is a bundle, if not assume it is not a bundle.

**Comment by tonis2** [comment]
@catshow 

Could you share your branch of rcodesign where you got the `Launchscreen` working ?
I'm trying to codesign a Flutter .app build, and I'm getting same error as you.

**Comment by indygreg** [comment]
I tried this with latest code, hoping it was magically fixed as a result of bundle signing refactoring. However, it is still buggy:

```
signing storyboard-test.app in place
signing bundle at storyboard-test.app
signing 2 nested bundles in the following order:
Base.lproj/LaunchScreen.storyboardc
Base.lproj/Main.storyboardc
entering nested bundle Base.lproj/LaunchScreen.storyboardc
signing bundle at storyboard-test.app/Base.lproj/LaunchScreen.storyboardc into storyboard-test.app/Base.lproj/LaunchScreen.storyboardc
Error: bundle Info.plist does not define CFBundleIdentifier: storyboard-test.app/Base.lproj/LaunchScreen.storyboardc/Info.plist
```

I _think_ the problem is that we're attempting to sign the `.storyboardc` directories as bundles because our bundle detector is detecting them as such. However, the project built by XCode didn't sign these directories as bundles and rather encapsulated their content in the `CodeResources` file.

I could come up with something quick and dirty here. But I need to think about this a bit more first.
